version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/GtMotive.Estimate.Microservice.Api/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: RentalDatabase
